name: AF3Builder CI

on:
  push:
    branches:
      - main
    tags:
      - '*'  # trigger on any tag

jobs:
  pyTests:
    name: Run pytest CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[actions]

      - name: Run tests
        run: |
          pytest tests/test_fetchers.py -v

  cli:
    name: CLI test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: af3build
        run: |
          af3build --help

      - name: af3map-chains
        run: |
          af3map-chains --help

      - name: af3estimate-tokens
        run: |
          af3estimate-tokens --help
